name: CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
#    - name: Select Xcode version
#      run: sudo xcode-select -s '/Applications/Xcode_10.3.app/Contents/Developer'
    - name: Show Xcode version
      run: xcodebuild -version
    - name: Run a one-line script
      run: ./get_frameworks.sh
